### ISSUE TITLE
Yammer Identity Providers documentation page is empty

### ISSUE THREAD

**Issue by jose-e-rodriguez** [auth0/docs#101]
Clicking the link to Yammer in the Identity Providers supported by Auth0 page (https://auth0.com/docs/identityproviders) sends to an empty documentation page (https://auth0.com/docs/connections/social/yammer)

![2015-06-07_1645](https://cloud.githubusercontent.com/assets/12707130/8025949/93619962-0d34-11e5-93c6-7616289221c0.png)
![2015-06-07_1644](https://cloud.githubusercontent.com/assets/12707130/8025948/936090f8-0d34-11e5-8fc2-ac7d6fcaac38.png)

**Comment by Catografix** [comment]
@ntotten Yammer requires a vertified company email address to sign-up. Is there an existing accout I could use to access the API and take screenshots to create this tutorial?

**Comment by Catografix** [comment]
@ntotten 

I found that Yammer SSO is being deprecated. I could insert this text to our yammer doc with a link to Office 365 doc: https://auth0.com/docs/connections/enterprise/o365-deprecated but that is also deprecated.

from: https://support.office.com/en-us/article/Office-365-sign-in-for-Yammer-b1745e3c-d4d7-4e20-a155-ebf85106b998

IMPORTANT   Yammer SSO is being deprecated and will stop working after December 1st, 2016. You will not be able to set up new configurations with Yammer SSO after April 1st, 2016. Instead of Yammer SSO, we recommend that you use Office 365 sign-in for Yammer.

**Comment by ntotten** [comment]
So Yammer SSO is different than Yammer OAuth. The docs that go with our yammer connection are here: https://developer.yammer.com/docs/oauth-2
