### ISSUE TITLE
connections page doesn't display

### ISSUE THREAD

**Issue by yvonnewilson** [auth0/docs#1126]
There is a directory in docs/articles called "connections" with an index.md file in it, but going to
https://auth0.com/docs/connections does not work.

This URL should work and provide links to all the connections docs inside the connections directory.

**Comment by mpaktiti** [comment]
Hello @yvonnewilson ! This `index.md` file is available under `https://auth0.com/docs/identityproviders` because this is how it is configured (url property is set to: `/identityproviders`). Let me know if you want this changed to `/connections`. This will affect other documents as well, with a search under `docs` repository I can see 17 other files referencing this link.

**Comment by jerriep** [comment]
If you change this URL, remember to set up redirects...

**Comment by mpaktiti** [comment]
Hi @yvonnewilson, I will close this issue since it has been inactive for some time, but if you need a redirect from `https://auth0.com/docs/connections` to `https://auth0.com/docs/identityproviders` let me know (or reopen this issue). Thanks!
