### ISSUE TITLE
AngularJS User Profile doc mentions non-existent directive if-not-user

### ISSUE THREAD

**Issue by JasonTheProgrammer** [auth0/docs#1920]
This file:
https://github.com/auth0/docs/blob/adf2d0c67c1aa8d49dfaa75c9428dace01e9d41a/articles/client-platforms/angularjs/03-user-profile.md

makes mention of an `if-not-user` directive, but no such directive exists. The `if-user` directive does exist, and works as described. That directives corresponding source file is here:
https://github.com/auth0/auth0-angular/blob/master/src/directives/ifUser.directive.js

It would be easy enough to create an `if-not-user` directive to mirror the `if-user` directive. I'm personally happy enough going directly to the `isAuthenticated` variable like this though:

`<p ng-show="isAuthenticated">Logged In</p>`
`<p ng-hide="isAuthenticated">Not Logged In</p>`

**Comment by mpaktiti** [comment]
https://techaid.atlassian.net/browse/AUTH-3260

**Comment by mpaktiti** [comment]
Assigned to TechAid.

**Comment by JasonTheProgrammer** [comment]
Sorry, I'm not clear on _why_ this issue was closed, could you explain @chenkie ?

**Comment by chenkie** [comment]
@JasonTheProgrammer with the auth0-angular SDK now deprecated, the docs are being updated to reflect usage with [angular-lock](https://github.com/auth0/angular-lock), [angular-auth0](https://github.com/auth0/angular-auth0), and [angular-jwt](https://github.com/auth0/angular-jwt). Since this directive was meant to be a part of auth0-angular and no longer will be, there isn't a need to have it in the docs.

Thanks for your willingness to create the directive :) If you find it to be useful then perhaps it's something we can add to [angular-jwt](https://github.com/auth0/angular-jwt) since we now have some auth manager related things there. I'd welcome PRs there if you're interested.

**Comment by JasonTheProgrammer** [comment]
Thanks for the clarification. Issues being closed without explanation is a pet-peeve of mine. I'll keep an eye on the angular-jwt project for opportunities to contribute.
