### ISSUE TITLE
Under Quickstarts - Issue with Plain links

### ISSUE THREAD

**Issue by pushpabrol** [auth0/docs#2417]
e.g. https://auth0.com/docs/quickstart/webapp/aspnet

The link under the "plain link" tab under the section `https://auth0.com/docs/quickstart/webapp/aspnet#4-triggering-login-manually-or-integrating-the-auth0lock` has an extra space after each line of text. If someone copies this url it will not work. I tried a link and each attribute in the url had a white space at the end. 

See image for example: 

![image](https://cloud.githubusercontent.com/assets/7750618/19025973/02d5fdac-88ee-11e6-8464-eb2c5e994db6.png)

**Comment by mpaktiti** [comment]
@pushpabrol Hey, it looks like it indeed, but when I copied the contents of `Plain Links` and pasted it in my text editor, I didn't get any whitespace at the end of the lines. There are at the beginnings but it looks intentional https://github.com/auth0/docs/blob/master/articles/_includes/_lock-sdk.html#L146

![image](https://cloud.githubusercontent.com/assets/11715799/19035338/a56c5f7e-8971-11e6-88bd-a485d96063ec.png)

@ntotten Can you have a look into this? Should we change something at the `_lock-sdk` code?

**Comment by ntotten** [comment]
We are optimizing for readability. The link is hard to understand if you display it as one string of text.
