### ISSUE TITLE
ASP.NET Core tutorial incorrect structure

### ISSUE THREAD

**Issue by vmartynets** [auth0/docs#2608]
(AUTH-3495)
[Contributing.md](https://github.com/auth0/docs/blob/master/CONTRIBUTING.md#web) describes structure of web app tutorial (Intro, Login, Login with Custom UI, Session Handling, etc), but [ASP.NET Core tutorial](https://auth0.com/docs/quickstart/webapp/aspnet-core) have different structure:
![image](https://cloud.githubusercontent.com/assets/1114365/19619485/6998c816-9871-11e6-8e42-7cdccda86f08.png)

**Comment by jerriep** [comment]
@chenkie Not sure that this is an issue. The ASP.NET Core QS has a special "Embedded Lock" section because there are special requirements for that scenario as the ASP.NET Core OIDC middleware enforces `state` and `nonce` checks which many other middleware does not do.

Can you please let me know whether I can go ahead and close this issue?
