### ISSUE TITLE
Grammatical errors in the NancyFX SDK quickstart

### ISSUE THREAD

**Issue by camimonse** [auth0/docs#3368]
In https://auth0.com/docs/quickstart/webapp/nancyfx there are some errors found:

- erase "s" --> ...let you set...
![image](https://cloud.githubusercontent.com/assets/18585436/22373961/31537242-e48b-11e6-8d2f-752898f3a399.png)

- Login --> log in
- Log out --> log out
![image](https://cloud.githubusercontent.com/assets/18585436/22374043/8b315b8a-e48b-11e6-8481-5f9c136e097b.png)

Because is a verb.

AUTH - 3367

**Comment by mpaktiti** [comment]
Changing `lets` to `let` doesn't look right. `Lets` is used in the third-person singular present tense, and `The UserIdentifier` is an `it`. If we used `allow` instead of `let`, we would say `It allows you to set an identifier for the user` (where It=The UserIdentifier).

I'm removing this change and merging the PR.
