### ISSUE TITLE
Python Code to Automate the Process of Management Tokens appears broken

### ISSUE THREAD

**Issue by fernando-mc** [auth0/docs#5939]
The example for Python here under automate the process doesn't appear to work: https://auth0.com/docs/api/management/v2/tokens#automate-the-process

I'd suggest something a lot cleaner like this:
```python
import requests
import json

headers = {"content-type": "application/json"}
payload = {
    "grant_type":"client_credentials",
    "client_id": "CLIENT_ID_VALUE",
    "client_secret": "CLIENT_SECRET_VALUE",
    "audience": "https://yourappurl.auth0.com/api/v2/"
}
url = 'https://yourappurl.auth0.com/oauth/token'

r = requests.post(url, headers=headers, data=json.dumps(payload))
`

**Comment by michizhou** [comment]
Hi @fernando-mc if it's alright, may I try to tackle this issue?

**Comment by fernando-mc** [comment]
@michizhou I'm just the person who filed the issue - go for it! Maybe ask @davidpatrick who it appears to be assigned to now.

**Comment by michizhou** [comment]
@davidpatrick would it be alright if I take this issue?

**Comment by michizhou** [comment]
Thanks @davidpatrick! As for the documentation itself, @fernando-mc I am not sure which Python code snippet you are referring to since the "automate the process" section does not seem to exist on this page. If the snippet you are referring to is not the one under "Sample Implementation: Python", could you please provide the GitHub repo path for the file with the snippet? Otherwise, I can't find it. Thanks!

**Comment by fernando-mc** [comment]
It's been ~6 months since I opened this, maybe it was fixed by now? I'll close this and reopen if I notice it again later.
