### ISSUE TITLE
Facebook login for forced v9 upgrade

### ISSUE THREAD

**Issue by ffischetti** [auth0/docs#5997]
With the  upgrade to Auth0.js v9, the facebook documentation hasn't changed at [/docs/connections/social/facebook](/docs/connections/social/facebook)

Under "Enter the following URL in the Valid OAuth redirect URIs field:"

The documentation still reads: `https://exampleapp.auth0.com/login/callback`

However, with the Auth0.js v9 upgrade, the [migration docs](/docs/libraries/auth0js/v9/migration-v8-v9#configure-your-custom-domain) seem to instruct us to change the callback url to a custom domain: `https://auth.exampleapp.com/login/callback`

Could you clarify in the documentation whether the custom domain callback is required as part of the upgrade?

In addition, adding the custom domain callback to facebook's whitelisted redirect urls doesn't seem to work, so additional or different documentation may be needed.  When trying facebook login, I get the error: 

> URL Blocked: This redirect failed because the redirect URI is not whitelisted in the app’s Client OAuth Settings. Make sure Client and Web OAuth Login are on and add all your app domains as Valid OAuth Redirect URIs.

**Comment by jeffreylees** [comment]
Hi! If you're using a custom domain, you'll need to set that custom domain in the redirect URIs in your Facebook settings, and make sure to use the custom domain in your Lock/Auth0.js code rather than your `auth0.com` one.

If that's not working, depending on your support level you'll want to open a support ticket / make a community post to further troubleshoot. The error you're getting sounds like the one that occurs when you don't have the custom domain callback in the redirect URI list for Facebook.

As for the docs, not everyone can use Custom Domains at the moment, so we probably won't be changing all instances of `auth0.com` URLs to be custom domains in the docs, but we will probably start adding notes in sections like these to remind custom domain users to use their custom domain instead of `auth0.com` address in case the change required isn't clear. Thanks for the feedback!
