### ISSUE TITLE
Unable to get access token using Resource Owner Password

### ISSUE THREAD

**Issue by johnnymetz** [auth0/docs#6177]
When trying to obtain an access token via the Resource Owner Password method, I keep getting the following 400 error:
```
{
    "error": "invalid_scope",
    "error_description": "User is not authorized to the audience for those scopes"
}
```

I'm making a POST request to `https://<tenant-name>.auth0.com/oauth/token` with the following payload:
```
{
  "grant_type": "password",
  "username": "<username>",
  "password": "<password>",
  "audience": "<api-audience>",
  "scope": "read:messages",
  "client_id": "<client-id>",
  "client_secret": "<client-secret>"
}
```
I'm using the default client application. I've tried the default API Audience (aka the Auth0 Management API) and a custom API Audience but no luck.

Any idea what I'm doing wrong here? I see there's a known bug [here](https://stackoverflow.com/questions/48999712/auth0-user-is-not-authorized-to-the-audience-for-those-scopes) but it appears to have been fixed already.

**Comment by johnnymetz** [comment]
Figured it out, I forgot the set the correct audience on the Resource Server. I was going through this tutorial: [here](https://auth0.com/docs/quickstart/backend/python/02-using)

You may close this issue.

**Comment by ravitheja04** [comment]
I am facing similar issue, when providing scopes. If I provide 'openid' 'profile' 'email' I get JWT, but when I provide 'id_token' & 'https://xxxxxxxx/authorization', I get above error log

**Comment by mpaktiti** [comment]
Hello @ravitheja04 👋 Since we, in the writing team, do not have the resources to properly troubleshoot customer issues, I'd advise you to contact our [Support](https://support.auth0.com/). [If you do not have a support plan](https://auth0.com/docs/support#support-options-overview), then you can use our [Community](https://community.auth0.com/). Once your issue is resolved, our colleagues will ping us about any updates we have to make in our docs. 
Alternatively, if you want to describe to me what you are trying to accomplish, maybe I can point you towards the right guidance for your implementation. I'm closing this for now but feel free to reopen.
