### ISSUE TITLE
Logout after refresh of PrivateRoute - React QuickStart Guide

### ISSUE THREAD

**Issue by joshghent** [auth0/docs#8072]
Hi there,
After following the react quickstart guide, I have found that if you refresh a `<PrivateRoute>` defined page, then it will send you to the Auth0 login screen. Further to this, when it redirects after logging in, the component defined for the `<PrivateRoute>` does not work. Any ideas on this one either?

Replication steps
1. Go to the unprotected `<Route>` page .e.g, "localhost:3000/"
2. Navigate to the protected `<PrivateRoute>` e.g., "localhost:3000/admin"
3. Login via Auth0 and get redirected back to the `<PrivateRoute>` page (in our example "/admin")
4. Refresh the page

What should happen if that the page just be refreshed, but in my case it goes back to the login screen, almost as if the login hasn't been saved in state. I am using the react-auth0-wrapper with React 16.8.6 created via `create-react-app`

Might be being dumb here but would appreciate your help! 👍 Thanks for all the great work you do

**Comment by cocojoe** [comment]
@alexisluque can you validate this please.

**Comment by alexisluque** [comment]
@cocojoe I could replicate this using social connection(Google and Github).
The problem is when reloading the page, silent auth is performed, and reading at [limitations of developers key](https://auth0.com/docs/connections/social/devkeys#limitations-of-developer-keys-when-using-classic-universal-login), this fails when using Auth0 developer keys.
Using my own keys for the social connection solved the problem.
This affects all SPA quickstarts.

**Comment by stevehobbsdev** [comment]
@joshghent This can happen for a few reasons:

* You're using a social connection with developer keys, and also the classic Universal Login Page
* You're using Safari (their ITP software will block the cookie you need in order to stay signed in)
* You're using some other software or browser (Chrome extension, Brave with its shields up, etc) that blocks the transmission of that cookie

Feel free to continue the converstion if you don't align with one of those scenarios.
